from backend.core.base import BaseArsenalModule
from backend.core.protocol import JobPacket, ResultPacket, Vulnerability, TaskTarget
# Hybrid AI Engine
from backend.ai.cortex import CortexEngine

cortex = CortexEngine()

class AuthBypassTester(BaseArsenalModule):
    def __init__(self):
        super().__init__()
        self.name = "Auth Bypass Tester"

    async def generate_payloads(self, packet: JobPacket) -> list[TaskTarget]:
        # 1. Try accessing without any headers (original)
        targets = []
        targets.append(TaskTarget(url=packet.target.url, method="GET", headers={}))
        
        # 2. HYBRID AI: Try AI-generated bypass headers
        ai_headers = await cortex.generate_auth_bypass_headers(packet.target.url)
        for bypass_set in ai_headers:
             targets.append(TaskTarget(url=packet.target.url, method="GET", headers=bypass_set))
             
        return targets

    async def analyze_responses(self, interactions: list[tuple[TaskTarget, str]], packet: JobPacket) -> list[Vulnerability]:
        vulnerabilities = []
        
        for idx, (target, text) in enumerate(interactions):
            if not isinstance(text, str): continue
            
            # Since we lost status == 200, we guess based on context.
            is_success = "admin" in text.lower() or "dashboard" in text.lower() or "welcome" in text.lower()
            if is_success:
                if idx == 0 and ("admin" in packet.target.url or "api/secure" in packet.target.url):
                    vulnerabilities.append(Vulnerability(
                        name="Broken Access Control (No Auth)",
                        severity="CRITICAL",
                        description="Secure endpoint accessible without credentials.",
                        evidence=f"GET {packet.target.url} without headers succeeded.",
                        remediation="Enforce authentication middleware on all secure routes."
                    ))
                elif idx > 0:
                    vulnerabilities.append(Vulnerability(
                        name="Auth Bypass (AI Header Injection)",
                        severity="HIGH",
                        description=f"Endpoint accessible with bypass headers: {list(target.headers.keys())}",
                        evidence=f"Headers: {target.headers}",
                        remediation="Validate auth tokens server-side, not via headers."
                    ))
                    break # One bypass is enough
        return vulnerabilities
